name: MineBackup
main: alexoft.Minebackup.MineBackup
author: ThisIsAreku
version: 0.4.5.1
description: Auto-backup your world(s) !
commands:
    mbck:
        description: make a backup
        usage: /mbck